// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/MonoAndroid/v8.0/Mono.Android.dll"
#r "C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/MonoAndroid/v1.0/System.Core.dll"
#r "C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/MonoAndroid/v1.0/System.dll"
#r "C:/Program Files (x86)/Reference Assemblies/Microsoft/Framework/MonoAndroid/v1.0/System.Xml.dll"
#r "../../packages/Xamarin.Android.Arch.Core.Common.1.0.0/lib/MonoAndroid80/Xamarin.Android.Arch.Core.Common.dll"
#r "../../packages/Xamarin.Android.Arch.Lifecycle.Common.1.0.1/lib/MonoAndroid80/Xamarin.Android.Arch.Lifecycle.Common.dll"
#r "../../packages/Xamarin.Android.Arch.Lifecycle.Runtime.1.0.0/lib/MonoAndroid80/Xamarin.Android.Arch.Lifecycle.Runtime.dll"
#r "../../packages/Xamarin.Android.FSharp.ResourceProvider.1.0.0.13/lib/Xamarin.Android.FSharp.ResourceProvider.Runtime.dll"
#r "../../packages/Xamarin.Android.Support.Annotations.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.Annotations.dll"
#r "../../packages/Xamarin.Android.Support.Compat.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.Compat.dll"
#r "../../packages/Xamarin.Android.Support.Core.UI.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.Core.UI.dll"
#r "../../packages/Xamarin.Android.Support.Core.Utils.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.Core.Utils.dll"
#r "../../packages/Xamarin.Android.Support.Fragment.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.Fragment.dll"
#r "../../packages/Xamarin.Android.Support.Media.Compat.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.Media.Compat.dll"
#r "../../packages/Xamarin.Android.Support.v4.26.1.0.1/lib/MonoAndroid80/Xamarin.Android.Support.v4.dll"